# -*- coding: utf-8 -*-
"""tugas2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Z_7h9kbMBdL5DIRIAqJvy1DzoxGGmqJ
"""

# Fungsi map_function
def map_function(text):
    for word in text.split():
        yield (word, 1)

# Fungsi reduce_function
from collections import defaultdict

def reduce_function(pairs):
    result = defaultdict(int)
    for word, count in pairs:
        result[word] += count
    return result

# Membaca dataset dari file fruity.txt
file_path = 'fruity.txt'
with open(file_path, 'r') as file:
    dataset = file.readlines()

# Menggunakan map_function pada dataset
mapped_pairs = []
for text in dataset:
    mapped_pairs.extend(list(map_function(text.strip())))

# Menggunakan reduce_function untuk menghitung jumlah kata
word_count = reduce_function(mapped_pairs)

# Menampilkan hasil
for word, count in word_count.items():
    print(f"{word}: {count}")