# -*- coding: utf-8 -*-
"""tugas5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Z_7h9kbMBdL5DIRIAqJvy1DzoxGGmqJ
"""

import csv

# Fungsi MapReduce
def mapreduce(file, kolom, mode='avg'):
    mapped_values = []

    # Baca file CSV
    with open(file, newline='') as csvfile:
        reader = csv.reader(csvfile)
        next(reader)  # Lewati header jika ada

        # Mapper: memetakan setiap baris CSV
        for line in reader:
            value = line[kolom]
            if mode == 'avg':
                try:
                    mapped_values.append((1, float(value)))  # (jumlah elemen, nilai)
                except ValueError:
                    continue
            elif mode == 'freq':
                mapped_values.append((value, 1))  # (elemen, 1)

    # Reducer: menghitung rata-rata atau frekuensi
    if mode == 'avg':
        count, total_sum = 0, 0.0
        for count_value, sum_value in mapped_values:
            count += count_value
            total_sum += sum_value
        result = total_sum / count if count > 0 else 0
        print(f"Rata-rata nilai: {result}")
    elif mode == 'freq':
        frequency_dict = {}
        for key, value in mapped_values:
            frequency_dict[key] = frequency_dict.get(key, 0) + value
        print("Frekuensi elemen:")
        for key, value in frequency_dict.items():
            print(f"{key}: {value}")

file = 'nilai.csv'
# Menghitung rata-rata kolom ke-2 (index 1)
mapreduce(file, kolom=1, mode='avg')
# Menghitung frekuensi kemunculan elemen pada kolom pertama (index 0)
mapreduce(file, kolom=0, mode='freq')